travis:
  secure:
    BINSTAR_TOKEN: NXOUM91vqrrizYuLGK2QehFF2VkxT2YivC/ZsC6TaZIyXQXnmD3Zb2e63Iwk19hjNv9U2k4LpAklrMbM1JmP1Xhhlz5s5fN2iVnu3NY4hXe0xENkxqr8SA7bLhqPX5rJPIe8SaCSbon8SE8PNm5nWs6L6iB4fkfGq3+r9DVGfKEvYDUYJLkpR+6gA+u5rGTkMls08PF6HTb4GCHYToqCq4W7XXt10Yu8M51837bKxKDV5m4RJrFPyjctRBipDPp6YZ7fpFIMP9ChbcBal0W6I6sGxxU2chj4nQklPEr+J9m9bUQip01TMSenlloUJD8/tJUrbWlkdbab5tcB28Ak8l/Kwo1TtFh2t+7950Z9DNuizfawaGoBF2N0ffHl5pQ9q9Y23Exn89JEosxjZWZLqjeNDeV4Ea8z2YsLLwop9NAKEN/QFpK6G4RQ0SqarH6SC/iBEdxlOp6c5pICbi97a3Q07wTLrGS82Ozmz3Ue1fVP3z1bdW80jH/c8PD9jvYrj+xoxXYyPEEvKvWgCfgZXAar22qTw5AQwhCLfVsqcHDYhNhNU3o92lD5ykNCeOTjh1spYv31nWNxsy0K2R55m2f8DEdnQQUSXn75IqL/LPeIUjB/gMyfOOOWJEv7xWL7r5OH3IiPZoDp3Jce5bTzfGi7NXQHCGnZDIDqIIc2USA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
